In [1]:
import numpy as np
y=np.array([1,2,4,5,6])
print(y)
y=np.insert(y,2,[3])
print(y)
x=np.array([[1,2,3],[7,8,9]])
print(x)
v=np.insert(x,1,[4,5,6],axis=0)
print(v)
w=np.insert(x,1,4,axis=1)
print(w)


[1 2 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 2 3]
 [7 4 8 9]]
